config/routes.rb
Rails.application.routes.draw do

  resources :polls
  match '/polls/:id/voting' => 'polls#voting', via: [:get], :as => :voting_poll
  match '/mypolls' => 'polls#my_index', via: [:get], :as => :my_polls
  post '/votes' => 'votes#create', via: [:post], :as => :new_votes

  resource 		:profile, only: [:show, :edit, :update ]
  resources 	:flats
  resources 	:posts
  resources   :chat_messages

  devise_for 	:users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users do
    resources :emails, only: [:index, :show, :new, :create, :destroy]
  end

  match 		'/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 			'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/poll.rb
class Poll < ApplicationRecord
	belongs_to :user
	has_many 						:options, -> { includes :votes }, dependent: :destroy
	accepts_nested_attributes_for 	:options
	validates_presence_of 			:title, :body, :user_id
	scope 							:opened, -> { where(status: 1) }
	scope 							:before, -> { where(status: 2) }
	scope 							:closed, -> { where(status: 3) }
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!
  before_filter :set_cache_headers, only: [:voting, :show ]
  before_action :set_poll,          only: [:voting, :show, :edit, :update, :destroy]
  before_action :set_editing_time,  only: [:edit, :show, :index, :my_index]
  before_action :user_can_vote?,    only: [:voting, :show]

  # Set editing poll time limit
  def set_editing_time
    @editing_time = 10.hour
  end

  # GET /polls
  # GET /polls.json
  # List of all polls in app
  def index
    @polls = Poll.all.order(status: :asc, created_at: :desc)
  end
  
  # List of all user's polls
  def my_index
    @polls = current_user.polls.order(status: :asc, created_at: :desc)
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    @option = Option.new
  end

  # GET /polls/1/edit
  def edit
    alert_string = ''
      if @poll.user != current_user
        alert_string = "You can edit only your own polls. "
        path = my_polls_path
      end
      if (DateTime.now.to_i - @poll.created_at.to_i) > @editing_time
        alert_string = alert_string + "Sorry! You can't edit this poll, 'cause editing time limit is over."
        path = @poll
      end     
      unless alert_string == ''
        respond_to do |format|
         format.html { redirect_to path, alert: alert_string }
        end
      end
  end

  # GET /polls/1/voting
  def voting
    unless user_can_vote?
      respond_to do |format|
        format.html { redirect_to @poll, alert: "You've voted for this poll." }
      end
    end  
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)
    # Now set Poll status eq. 1 for testing. 
    # All statuses: 1 = 'open'; 2 = 'before'; 3 = 'closed'
    @poll.status = 2
    @poll.user = current_user

    respond_to do |format|
      if check_poll_datetime && @poll.save && save_poll_options
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params) && save_poll_options #&& check_poll_datetime
        #save_poll_options
        byebug
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: "Poll \##{@poll.id} was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  # Chech if all options are empty
  def options_empty?
    params[:options].each do |option|
      if option != ""
        return false
      else
        return true
      end
    end  
  end
  
  # Save poll options
  def save_poll_options
    if options_empty?
      flash[:alert] = "You set no options. Have to add options!"
      return false
    else
    if @poll.options.empty?
      params[:options].each do |option|
        if option != ""
          new_option = Option.new(:poll_option => option, :poll_id => @poll.id)
          new_option.save!
        end
      end
    else
      params[:options].each do |key, value|
        if value != ""
          update_option = Option.where(:id => key.to_i).first
          update_option.poll_option = value
          update_option.save!
        end
      end
    end
    return true
    end
  end
  
  # Check can user vote or not? 
  def user_can_vote?
    @poll.options.each do |poll_option|
      if poll_option.votes.pluck(:user_id).include? current_user.id
        @voted = true
        false
        return
      else
        @voted = false
        true
      end
    end  
  end

  private
    # Reloads voting & show pages to prevent poll cheating
    def set_cache_headers
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end
    
    # Validates start & finish datetimes
    def check_poll_datetime
      if @poll.finish > @poll.start && @poll.start > DateTime.now && @poll.finish > DateTime.now 
        return true 
      else
        flash[:alert] = "You set the wrong start or finish time."
        return false
      end
    end
    
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:title, :body, :start, :finish, :status, :poll_type, :user_id)#, options_attributes: [:poll_option])
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= simple_form_for(@poll) do |f| %>
  <%= f.error_notification %>
    <%= action_name %>
    <%= f.input :title, label: 'Title', autocomplete: "off", placeholder: "Add your question here" %> 
    <%= f.input :body, label: 'Body', autocomplete: "off", placeholder: "Add your description here", 
    :input_html => {rows: 7} %>
    <%= f.input :start, start_year: Time.now.year, 
    order: [:day, :month, :year, :hour, :minute], minute_step: 30 %>
    <%= f.input :finish, start_year: Time.now.year, 
    order: [:day, :month, :year, :hour, :minute], minute_step: 30 %>
    
    <% case action_name %>
      <% when 'new' %>
        <%= f.input :poll_type, as: :select, collection: 
                    [['RadioButtons', 1], ['Multiply CheckBoxes', 2]], selected: 'RadioButtons' %>
        <p><b>Options (min. 2):</b></p>
        <div>
          Option 1<br>
          <input class="string optional form-control" type="text" name="options[]" id="options" autocomplete="off">
        </div>
        <div id="dynamicInput">
          Option 2<br>
          <input class="string optional form-control" type="text" name="options[]" id="options" autocomplete="off">
        </div>
        <br>
        <input type="button" class="btn btn-primary" value="Add another option (max. 20)" onClick="addInput('dynamicInput');">
        <p></p>
      <% when 'edit', 'create', 'update' %>
        <%= f.input :poll_type, as: :select, collection: 
                    [['RadioButtons', 1], ['Multiply CheckBoxes', 2]], selected: "#{@poll.poll_type}" %>
        <p><b>Options:</b></p>
        <% @poll.options.each_with_index do |option, index| %>
          <%= f.label "Option #{index + 1}" %> 
          <input class="string optional form-control" type="text" name="options[<%= option.id %>]" id="options_poll_option" value="<%= option.poll_option %>">
        <% end %>
        <% if @poll.options.empty? %>
        <div id="dynamicInputEdit">
          Option <%= @poll.options.count + 1 %><br>
          <input class="string optional form-control" type="text" name="options[]" id="options" autocomplete="off">
        </div>
        <br>
        <input type="button" class="btn btn-primary" value="Add another option (max 20)" onClick="addInputEdit('dynamicInputEdit');">
        <% end %>
        <p></p>
    <% end %>

  <p><i>Remember! You have 15 minutes after creating to edit the poll.</i></p>
  <div class="form-actions">
    <%= f.submit "Save Poll", class: "btn btn-lg btn-success" %>
  </div>
<% end %>
<br>

app/views/polls/_list.html.erb
<% @polls.each do |poll| %>
    <h3><%= link_to "#{poll.title}", poll_path(poll) %></h3>
    <p><b>Body:</b> <%= truncate(poll.body, length: 100) %></p>

    <p><b>Start:</b> <%= poll.start.to_formatted_s(:long_ordinal) %></p>
    <p><b>Finish:</b> <%= poll.finish.to_formatted_s(:long_ordinal) %></p>
    
    <p><b>Poll Type:</b> 
    <% case poll.poll_type %>
      <% when 1 %>
      <span>RadioButtons</span>
      <% when 2 %>
      <span>Multiply CheckBoxes</span>
    <% end %>
    </p>
    <p><b>User:</b> <%= poll.user_id %></p>
    <p><b>Poll ID:</b> <%= poll.id %></p>
    
    <p><b>Options:</b></p>
    <% poll.options.each_with_index do |option, index| %>
      <p>Opt. <%= index + 1 %>: <b><%= option.poll_option %></b>
      <% if poll.status == 3 %>
        <b> &rArr; <span style="color: orange">
        <%= Vote.where(:option_id => option.id).count %>
        </span></b></p>
      <% end %> 
    <% end %>

    <p><b>Poll Status:</b> 
    <% case poll.status %>
      <% when 2 %> 
      <span style="color: orange">Voting will start at <%= poll.start.to_formatted_s(:long_ordinal) %></span>
      <% when 1 %> 
      <span style="color: dodgerblue">Voting is in progress. Open 'til <%= poll.finish.to_formatted_s(:long_ordinal) %></span>
      <% when 3 %>
      <span style="color: red">Voting was closed at <%= poll.finish.to_formatted_s(:long_ordinal) %></span>
    <% end %>
    </p>
    <% if poll.user == current_user %>
      <%= link_to 'Show', poll %> |
      <% if (DateTime.now.to_i - poll.created_at.to_i) < @editing_time %>
        <%= link_to 'Edit', edit_poll_path(poll) %> | 
      <% end %>
      <%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <hr />
  <% end %>

<br>

<% if @polls.size == 0 %>
  <% case action_name %>
    <% when 'index' %>
      <p>There's absolutely no polls. <%= link_to "It's time to create one", new_poll_path %>.</p>
    <% when 'my_index' %>
        <p>You don't have any polls. <%= link_to "It's time to create one", new_poll_path %>.</p>
  <% end %>
<% end %>
<%= button_to "Create New Poll", new_poll_path, method: :get, class: "btn btn-lg btn-primary" %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<!--p id="notice"><%= notice %></p-->

<h1>All Polls</h1>

<%= render 'list', object: @action_type %>

app/views/polls/my_index.html.erb
<!--p id="notice"><%= notice %></p-->

<h1>My Polls</h1>

<%= render 'list', object: @action_type %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'All Polls', polls_path %>

app/views/polls/show.html.erb
<!--p id="notice"><%= notice %></p-->

<h3><%= @poll.title %></h3>
<p><b>Body:</b> <%= @poll.body %></p>
<p><b>Start:</b> <%= @poll.start.to_formatted_s(:long_ordinal) %></p>
<p><b>Finish:</b> <%= @poll.finish.to_formatted_s(:long_ordinal) %></p>
    
<p><b>Poll Type:</b> 
  <% case @poll.poll_type %>
    <% when 1 %>
      <span>RadioButtons</span>
    <% when 2 %>
      <span>Multiply CheckBoxes</span>
  <% end %>
</p>

<p><b>User:</b> <%= @poll.user_id %></p>

<p><b>Poll ID:</b> <%= @poll.id %></p>

<p><b>Options:</b></p>
<% @poll.options.each_with_index do |option, index| %>
  <p>Opt. <%= index + 1 %>: <b><%= option.poll_option %></b>
  <% if @voted || @poll.status == 3 %>
    <b> &rArr; <span style="color: orange">
    <%= Vote.where(:option_id => option.id).count %>
    </span></b></p>
  <% end %> 
<% end %>

<p><b>Poll Status:</b> 
  <% case @poll.status %>
    <% when 2 %> 
      <span style="color: orange">Voting will start at <%= @poll.start.to_formatted_s(:long_ordinal) %></span>
    <% when 1 %> 
      <span style="color: dodgerblue">Voting is in progress. Open 'til <%= @poll.finish.to_formatted_s(:long_ordinal) %></span>
      <% unless @voted %>
        <%= button_to "Vote now!", voting_poll_path(@poll), method: :get, class: "btn btn-primary" %>
      <% else %>
        <p style="color: red"><b>You've already voted for this poll.</b></p>
      <% end %>
    <% when 3 %>
      <span style="color: red">Voting was closed at <%= @poll.finish.to_formatted_s(:long_ordinal) %></span>
  <% end %>
</p>

<% if @poll.user == current_user %>
  <% if (DateTime.now.to_i - @poll.created_at.to_i) < @editing_time %>
    <%= link_to 'Edit', edit_poll_path(@poll) %> | 
  <% end %> 
  <%= link_to 'Destroy', @poll, method: :delete, data: { confirm: 'Are you sure?' } %> | 
  <%= link_to 'All Polls', polls_path %> | 
  <%= link_to 'My Polls', my_polls_path %>
<% end %>
<p></p>
<p align="center"><%= link_to '< Prev. Poll', Poll.where("id < ?", @poll.id).last %>
&nbsp;&nbsp;...&nbsp;&nbsp;&nbsp;<%= link_to 'Next Poll >', Poll.where("id > ?", @poll.id).first %></p>

app/views/polls/voting.html.erb
<% if @poll.status != 1 %>
	
	<h2 style="color: red">This poll is not open now.</h2>

<% else %>

	<h1><%= @poll.title %></h1>
	<p>User ID: <%= @poll.user_id %></p>
	<p>Poll ID: <%= @poll.id %></p>
	<p>Body: <%= @poll.body %></p>
	<p>Start: <%= @poll.start.to_formatted_s(:long_ordinal) %></p>
	<p>Finish: <%= @poll.finish.to_formatted_s(:long_ordinal) %></p>
	    
	<p>Poll Status: 
	  <% case @poll.status %>
	    <% when 2 %> 
	      <span style="color: orange">Voting will start at <%= @poll.start.to_formatted_s(:long_ordinal) %></span>
	    <% when 1 %> 
	      <span style="color: dodgerblue">Voting is in progress. Open 'til <%= @poll.finish.to_formatted_s(:long_ordinal) %></span>
	    <% when 3 %>
	      <span style="color: red">Voting was closed at <%= @poll.finish.to_formatted_s(:long_ordinal) %></span>
	  <% end %>
	</p>
	    
	<p>Poll Type: 
	  <% case @poll.poll_type %>
	    <% when 1 %>
	      <span>RadioButtons</span>
	    <% when 2 %>
	      <span>Multiply CheckBoxes</span>
	  <% end %>
	</p>

	<p><b>Options:</b></p>  
	<!--% @option_collection = @poll.options %-->

  	<%= form_tag "/votes" do |f| %>
		<% case @poll.poll_type %>
	    	<% when 1 %>
				<% @poll.options.each do |option| %>
				<div class="field form-group">
			  		<%= label_tag "poll_option_#{option.id}", class: "radio" do %>
		            	<%= radio_button_tag("options", option.id, checked = false) %><%= option.poll_option %>
		            <% end %>
			  	</div>
				<% end %>
		    <% when 2 %>
				<% @poll.options.each do |option| %>
				<div class="field form-group">
			  		<%= label_tag "poll_option_#{option.id}" do %>
		            	<%= check_box("options", option.id) %> <%= option.poll_option %>
		            <% end %>
			  	</div>
				<% end %>
		<% end %>
	  <%= submit_tag "VOTE!", class: "btn btn-lg btn-success" %>
	  <br><br>
	<% end %>

<% end %>
<%= link_to 'All Polls', polls_path %>